apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: p5ci
  namespace: default
spec:
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  workspaces:
  - name: shared-data
  - name: git-credentials
  - name: docker-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      - name: ssh-directory
        workspace: git-credentials
      params:
      - name: url
        value: $(params.repo-url)
    
    - name: run-tests
      runAfter: ["fetch-source"]
      taskRef:
        name: run-tests
      workspaces:
      - name: source
        workspace: shared-data

    - name: build-push-django
      runAfter: ["run-tests"]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: shared-data
      - name: dockerconfig
        workspace: docker-credentials
      params:
      - name: IMAGE
        value: $(params.image-reference)/django-auth:$(tasks.fetch-source.results.committer-date)-$(tasks.fetch-source.results.commit)
      - name: DOCKERFILE
        value: ./django-authentication/docker/Dockerfile
      - name: CONTEXT
        value: ./django-authentication

    - name: build-push-llm
      runAfter: ["run-tests"]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: shared-data
      - name: dockerconfig
        workspace: docker-credentials
      params:
      - name: IMAGE
        value: $(params.image-reference)/llm:$(tasks.fetch-source.results.committer-date)-$(tasks.fetch-source.results.commit)
      - name: DOCKERFILE
        value: ./llm_server/docker/Dockerfile
      - name: CONTEXT
        value: ./llm_server
    
    - name: scan-dep-llm
      runAfter: ["build-push-llm"]
      taskRef:
        name: grype
      workspaces:
      - name: dockerconfig
        workspace: docker-credentials
      params:
      - name: ARGS
        value:
        - "$(tasks.build-push-llm.results.IMAGE_URL)"
  
    - name: scan-dep-django
      runAfter: ["build-push-django"]
      taskRef:
        name: grype
      workspaces:
      - name: dockerconfig
        workspace: docker-credentials
      params:
      - name: ARGS
        value:
        - "$(tasks.build-push-django.results.IMAGE_URL)"