apiVersion: v1
kind: Service
metadata:
  name: llmapp-service
  labels:
    app: generic-app
spec:
  selector:
    app: generic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP