# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmproto.v1 import llm_pb2 as llmproto_dot_v1_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llmproto/v1/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """LLMService defines the gRPC service for language model completions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Completion = channel.unary_unary(
                '/llmproto.v1.LLMService/Completion',
                request_serializer=llmproto_dot_v1_dot_llm__pb2.CompletionRequest.SerializeToString,
                response_deserializer=llmproto_dot_v1_dot_llm__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.LLMStream = channel.unary_stream(
                '/llmproto.v1.LLMService/LLMStream',
                request_serializer=llmproto_dot_v1_dot_llm__pb2.LLMStreamRequest.SerializeToString,
                response_deserializer=llmproto_dot_v1_dot_llm__pb2.LLMStreamResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """LLMService defines the gRPC service for language model completions.
    """

    def Completion(self, request, context):
        """Completion generates a completion based on the provided request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LLMStream(self, request, context):
        """LLMStream generates a streaming completion based on the provided request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Completion': grpc.unary_unary_rpc_method_handler(
                    servicer.Completion,
                    request_deserializer=llmproto_dot_v1_dot_llm__pb2.CompletionRequest.FromString,
                    response_serializer=llmproto_dot_v1_dot_llm__pb2.CompletionResponse.SerializeToString,
            ),
            'LLMStream': grpc.unary_stream_rpc_method_handler(
                    servicer.LLMStream,
                    request_deserializer=llmproto_dot_v1_dot_llm__pb2.LLMStreamRequest.FromString,
                    response_serializer=llmproto_dot_v1_dot_llm__pb2.LLMStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmproto.v1.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmproto.v1.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """LLMService defines the gRPC service for language model completions.
    """

    @staticmethod
    def Completion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmproto.v1.LLMService/Completion',
            llmproto_dot_v1_dot_llm__pb2.CompletionRequest.SerializeToString,
            llmproto_dot_v1_dot_llm__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LLMStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llmproto.v1.LLMService/LLMStream',
            llmproto_dot_v1_dot_llm__pb2.LLMStreamRequest.SerializeToString,
            llmproto_dot_v1_dot_llm__pb2.LLMStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
