# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmproto/v1/llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llmproto/v1/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15llmproto/v1/llm.proto\x12\x0bllmproto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n\x11\x43ompletionRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x10LLMStreamRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xb5\x01\n\x12\x43ompletionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12+\n\x07\x63reated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05model\x18\x04 \x01(\t\x12!\n\x05usage\x18\x05 \x01(\x0b\x32\x12.llmproto.v1.Usage\x12$\n\x07\x63hoices\x18\x06 \x03(\x0b\x32\x13.llmproto.v1.Choice\"\x91\x01\n\x11LLMStreamResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12+\n\x07\x63reated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05model\x18\x04 \x01(\t\x12$\n\x07\x63hoices\x18\x05 \x03(\x0b\x32\x13.llmproto.v1.Choice\"O\n\x05Usage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\"N\n\x06\x43hoice\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x10\n\x08logprobs\x18\x03 \x01(\t\x12\x15\n\rfinish_reason\x18\x04 \x01(\t2\xa9\x01\n\nLLMService\x12M\n\nCompletion\x12\x1e.llmproto.v1.CompletionRequest\x1a\x1f.llmproto.v1.CompletionResponse\x12L\n\tLLMStream\x12\x1d.llmproto.v1.LLMStreamRequest\x1a\x1e.llmproto.v1.LLMStreamResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmproto.v1.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLETIONREQUEST']._serialized_start=71
  _globals['_COMPLETIONREQUEST']._serialized_end=107
  _globals['_LLMSTREAMREQUEST']._serialized_start=109
  _globals['_LLMSTREAMREQUEST']._serialized_end=144
  _globals['_COMPLETIONRESPONSE']._serialized_start=147
  _globals['_COMPLETIONRESPONSE']._serialized_end=328
  _globals['_LLMSTREAMRESPONSE']._serialized_start=331
  _globals['_LLMSTREAMRESPONSE']._serialized_end=476
  _globals['_USAGE']._serialized_start=478
  _globals['_USAGE']._serialized_end=557
  _globals['_CHOICE']._serialized_start=559
  _globals['_CHOICE']._serialized_end=637
  _globals['_LLMSERVICE']._serialized_start=640
  _globals['_LLMSERVICE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
