apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imagerepository-llm.yaml
  - imagerepository-login.yaml
  - imagepolicy-llm.yaml
  - imagepolicy-login.yaml
  - imageupdateautomation.yaml