apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: llm-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        serving.knative.dev/progress-deadline: "600s" 
    spec:
      containerConcurrency: 1
      containers:
      - image: cloudnativeacr.azurecr.io/llmapp:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthcheck
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5