apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: login
  namespace: flux-system
spec:
  image: cloudnativeacr.azurecr.io/django-auth
  interval: 2m
  provider: generic
  secretRef:
    name: flux-acr-auth